USE VENTAS;
GO
-- CREACION DE LA VISTA
-- Crear la vista sin la cláusula ORDER BY
CREATE VIEW CONSULTA_ANIO_UNIDADES AS
SELECT YEAR(V.FECHA_HORA) AS ANIO, SUM(UNIDADES) AS UNIDADES
FROM VENTAS V
GROUP BY YEAR(V.FECHA_HORA);
GO

-- Consultar la vista
SELECT * FROM CONSULTA_ANIO_UNIDADES;
